export const DashboardSummaryMock = {
  vehicleCount: 28,
  driverCount: 34,
  missionCount: 182,
  expenseCount: 56,

  activeVehicles: 24,

  inactiveVehicles: 4,

  runningMissions: 18,

  completedMissions: 164,

  monthlyExpense: 48500,

  monthlyFuelCost: 21200,
};
export const FuelConsumptionMock = [
  {
    id: 1,
    day: '1',
    vehicleId: 1,
    driverId: 1,
    missionId: 1,

    fuelType: 'Diesel',

    date: '2026-02-01',

    fuel: 320,
  },

  {
    id: 2,
    day: '5',
    vehicleId: 2,
    driverId: 1,
    missionId: 3,

    fuelType: 'Gasoline',

    date: '2026-04-05',

    fuel: 410,
  },

  {
    id: 3,
    day: '10',
    vehicleId: 2,
    driverId: 2,
    missionId: 3,

    fuelType: 'Gasoline',

    date: '2026-01-05',

    fuel: 280,
  },

  {
    id: 4,
    day: '15',
    vehicleId: 1,
    driverId: 1,
    missionId: 3,

    fuelType: 'Gasoline',

    date: '2026-03-05',

    fuel: 500,
  },

  {
    id: 5,
    day: '20',
    vehicleId: 2,
    driverId: 2,
    missionId: 1,

    fuelType: 'Gasoline',

    date: '2026-05-05',

    fuel: 360,
  },

  {
    id: 6,
    day: '25',
    vehicleId: 2,
    driverId: 2,
    missionId: 1,

    fuelType: 'Gasoline',

    date: '2026-05-05',

    fuel: 430,
  },

  {
    id: 7,
    day: '30',
    vehicleId: 1,
    driverId: 2,
    missionId: 1,

    fuelType: 'Gasoline',

    date: '2026-03-01',

    fuel: 390,
  },
];

export const ExpenseMock = [
  {
    id: 1,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-01-10',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },

  {
    id: 2,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: null,
    fuelRecordId: null,
    expenseDate: '2026-02-14',
    amount: 350,
    invoiceNumber: 'EXP002',
    description: '....',
  },
  {
    id: 3,
    vehicleId: 3,
    expenseTypeId: 1,
    vendorId: 2,
    fuelRecordId: null,
    expenseDate: '2026-04-10',
    amount: 170,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 4,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-02-10',
    amount: 250,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 5,
    vehicleId: 2,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-04-10',
    amount: 151,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 6,
    vehicleId: 2,
    expenseTypeId: 3,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-02-10',
    amount: 350,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 7,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-05-10',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 8,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-08-10',
    amount: 190,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 9,
    vehicleId: 1,
    expenseTypeId: 3,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-11-10',
    amount: 220,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 10,
    vehicleId: 2,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-12-10',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 11,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-01-15',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },

  {
    id: 12,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: null,
    fuelRecordId: null,
    expenseDate: '2026-02-24',
    amount: 350,
    invoiceNumber: 'EXP002',
    description: '....',
  },
  {
    id: 13,
    vehicleId: 3,
    expenseTypeId: 1,
    vendorId: 2,
    fuelRecordId: null,
    expenseDate: '2026-04-16',
    amount: 170,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 14,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-02-02',
    amount: 250,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 15,
    vehicleId: 2,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-04-20',
    amount: 151,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 16,
    vehicleId: 2,
    expenseTypeId: 3,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-02-29',
    amount: 350,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 17,
    vehicleId: 1,
    expenseTypeId: 2,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-05-04',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 18,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-08-22',
    amount: 190,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 19,
    vehicleId: 1,
    expenseTypeId: 3,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-11-01',
    amount: 220,
    invoiceNumber: 'EXP001',
    description: '....',
  },
  {
    id: 20,
    vehicleId: 2,
    expenseTypeId: 1,
    vendorId: 1,
    fuelRecordId: null,
    expenseDate: '2026-12-26',
    amount: 150,
    invoiceNumber: 'EXP001',
    description: '....',
  },
];
export const MonthlyDistanceMock = [
  {
    id: 1,
    vehicleId: 1,
    driverId: 1,
    missionId: 1,
    missionDate: '2026-01-05',
    distanceKm: 450,
  },

  {
    id: 2,
    vehicleId: 1,
    driverId: 1,
    missionId: 2,
    missionDate: '2026-01-18',
    distanceKm: 780,
  },

  {
    id: 3,
    vehicleId: 2,
    driverId: 2,
    missionId: 3,
    missionDate: '2026-02-12',
    distanceKm: 350,
  },

  {
    id: 4,
    vehicleId: 3,
    driverId: 2,
    missionId: 4,
    missionDate: '2026-03-10',
    distanceKm: 1200,
  },

  {
    id: 5,
    vehicleId: 1,
    driverId: 3,
    missionId: 5,
    missionDate: '2026-03-20',
    distanceKm: 900,
  },

  {
    id: 6,
    vehicleId: 2,
    driverId: 1,
    missionId: 6,
    missionDate: '2026-04-08',
    distanceKm: 650,
  },

  {
    id: 7,
    vehicleId: 4,
    driverId: 4,
    missionId: 7,
    missionDate: '2026-05-17',
    distanceKm: 1400,
  },

  {
    id: 8,
    vehicleId: 3,
    driverId: 2,
    missionId: 8,
    missionDate: '2026-06-22',
    distanceKm: 800,
  },

  {
    id: 9,
    vehicleId: 1,
    driverId: 1,
    missionId: 9,
    missionDate: '2026-07-03',
    distanceKm: 950,
  },

  {
    id: 10,
    vehicleId: 5,
    driverId: 5,
    missionId: 10,
    missionDate: '2026-08-15',
    distanceKm: 700,
  },

  {
    id: 11,
    vehicleId: 2,
    driverId: 3,
    missionId: 11,
    missionDate: '2026-09-07',
    distanceKm: 1100,
  },

  {
    id: 12,
    vehicleId: 4,
    driverId: 2,
    missionId: 12,
    missionDate: '2026-10-18',
    distanceKm: 600,
  },

  {
    id: 13,
    vehicleId: 1,
    driverId: 1,
    missionId: 13,
    missionDate: '2026-11-09',
    distanceKm: 1350,
  },

  {
    id: 14,
    vehicleId: 3,
    driverId: 4,
    missionId: 14,
    missionDate: '2026-12-21',
    distanceKm: 850,
  },
];
export const VehicleUsageMock = [
  {
    day: '1',
    usage: 72,
  },
  {
    day: '5',
    usage: 68,
  },
  {
    day: '10',
    usage: 81,
  },
  {
    day: '15',
    usage: 77,
  },
  {
    day: '20',
    usage: 84,
  },
  {
    day: '25',
    usage: 79,
  },
  {
    day: '30',
    usage: 86,
  },
];

export const DriverPerformanceMock = [
  {
    driver: 'احمدی',
    score: 92,
  },
  {
    driver: 'محمدی',
    score: 88,
  },
  {
    driver: 'کریمی',
    score: 84,
  },
  {
    driver: 'حسینی',
    score: 81,
  },
  {
    driver: 'رضایی',
    score: 78,
  },
];
export const LatestActivitiesMock = [
  {
    id: 1,
    driverId: 1,
    vehicleId: 2,
    activity: 'ثبت سوخت',
    user: 'احمدی',
    date: '2026-04-18',
    time: '08:35',
  },
  {
    id: 2,
    driverId: 2,
    vehicleId: 2,
    activity: 'ثبت مأموریت',
    user: 'محمدی',
    date: '2026-06-18',
    time: '09:20',
  },
  {
    id: 3,
    driverId: 3,
    vehicleId: 2,
    activity: 'ثبت هزینه تعمیر',
    user: 'کریمی',
    date: '1405-04-18',
    time: '10:15',
  },
  {
    id: 4,
    driverId: 1,
    vehicleId: 3,
    activity: 'پایان مأموریت',
    user: 'حسینی',
    date: '2026-04-18',
    time: '11:40',
  },
];
export const VehicleMock = [
  {
    id: 1,
    driverId: 1,
    vehicleId: 1,
    plateNumber: '21الف345-67',
    vehicleName: 'ولوو FH500',
    driverName: 'احمد احمدی',
    odometer: 245630,
    status: 'فعال',
  },
  {
    id: 2,
    driverId: 3,
    vehicleId: 3,
    plateNumber: '18ب456-21',
    vehicleName: 'اسکانیا R450',
    driverName: 'رضا محمدی',
    odometer: 182450,
    status: 'در مأموریت',
  },
  {
    id: 3,
    driverId: 2,
    vehicleId: 2,
    plateNumber: '54ج789-11',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    odometer: 96450,
    status: 'تعمیرگاه',
  },
];
export const DriversMock = [
  {
    id: 1,
    driverId: 1,
    fullName: 'احمد احمدی',
    nationalCode: '1234567890',
    phoneNumber: '09121234567',
    missionCount: 18,
    isActive: 'true',
  },
  {
    id: 2,
    driverId: 2,
    fullName: 'رضا محمدی',
    nationalCode: '2234567890',
    phoneNumber: '09123334444',
    missionCount: 22,
    isActive: 'true',
  },
  {
    id: 3,
    driverId: 3,
    fullName: 'علی کریمی',
    nationalCode: '3234567890',
    phoneNumber: '09125556666',
    missionCount: 14,
    isActive: 'false',
  },
];
export const FuelRecordMock = [
  {
    id: 1,
    driverId: 1,
    vehicleId: 1,
    fuelDate: '2026-01-18',
    vehicleName: 'ولوو FH500',
    driverName: 'احمدی',
    fuelAmount: 320,
    totalCost: 10800,
    stationName: 'جایگاه آزادی',
  },
  {
    id: 2,
    driverId: 2,
    vehicleId: 3,
    fuelDate: '2026-09-18',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    fuelAmount: 285,
    totalCost: 9640,
    stationName: 'جایگاه بعثت',
  },
  {
    id: 3,
    driverId: 1,
    vehicleId: 3,
    fuelDate: '2026-03-18',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    fuelAmount: 285,
    totalCost: 9640,
    stationName: 'جایگاه بعثت',
  },
  {
    id: 4,
    driverId: 3,
    vehicleId: 3,
    fuelDate: '2026-12-18',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    fuelAmount: 285,
    totalCost: 9640,
    stationName: 'جایگاه بعثت',
  },
  {
    id: 5,
    driverId: 2,
    vehicleId: 1,
    fuelDate: '2026-02-18',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    fuelAmount: 285,
    totalCost: 9640,
    stationName: 'جایگاه بعثت',
  },
  {
    id: 6,
    driverId: 2,
    vehicleId: 3,
    fuelDate: '2026-01-18',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    fuelAmount: 285,
    totalCost: 9640,
    stationName: 'جایگاه بعثت',
  },
];
export const ExpensesMock = [
  {
    id: 1,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    expenseDate: '1405/04/18',
    expenseType: 'تعمیرات',
    vehicleName: 'ولوو FH500',
    driverName: 'احمدی',
    amount: 1250,
    status: 'Approved',
  },
  {
    id: 2,
    vehicleId: 1,
    expenseTypeId: 1,
    vendorId: 1,
    expenseDate: '1405/04/18',
    expenseType: 'لاستیک',
    vehicleName: 'اسکانیا R450',
    driverName: 'محمدی',
    amount: 4200,
    status: 'Pending',
  },
  {
    id: 3,
    vehicleId: 2,
    expenseTypeId: 1,
    vendorId: 1,
    expenseDate: '2026-04-17',
    expenseType: 'روغن موتور',
    vehicleName: 'ایسوزو NPR',
    driverName: 'کریمی',
    amount: 580,
    status: 'Rejected',
  },
];
export const MissionMock = [
  {
    id: 1,
    vehicleId: 2,
    driverId: 1,
    missionId: 1,
    missionNumber: 'M-1001',
    vehicleName: 'ولوو FH500',
    driverName: 'احمد احمدی',
    origin: 'تهران',
    destination: 'اصفهان',
    missionDate: '2026-05-18',
    status: 'Running',
  },
  {
    id: 2,
    vehicleId: 2,
    driverId: 2,
    missionId: 1,
    missionNumber: 'M-1002',
    vehicleName: 'اسکانیا R450',
    driverName: 'رضا محمدی',
    origin: 'تبریز',
    destination: 'تهران',
    missionDate: '2026-04-18',
    status: 'Completed',
  },
  {
    id: 3,
    vehicleId: 3,
    driverId: 1,
    missionId: 1,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-12-17',
    status: 'Cancelled',
  },
  {
    id: 4,
    vehicleId: 2,
    driverId: 1,
    missionId: 1,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-04-17',
    status: 'Cancelled',
  },
  {
    id: 5,
    vehicleId: 3,
    driverId: 1,
    missionId: 1,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-01-17',
    status: 'Cancelled',
  },
  {
    id: 6,
    vehicleId: 3,
    driverId: 1,
    missionId: 1,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-02-17',
    status: 'Cancelled',
  },
  {
    id: 7,
    vehicleId: 3,
    driverId: 1,
    missionId: 2,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-09-17',
    status: 'Cancelled',
  },
  {
    id: 8,
    vehicleId: 3,
    driverId: 1,
    missionId: 3,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-08-17',
    status: 'Cancelled',
  },
  {
    id: 9,
    vehicleId: 3,
    driverId: 1,
    missionId: 3,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-07-17',
    status: 'Cancelled',
  },
  {
    id: 10,
    vehicleId: 3,
    driverId: 1,
    missionId: 2,
    missionNumber: 'M-1003',
    vehicleName: 'ایسوزو NPR',
    driverName: 'علی کریمی',
    origin: 'مشهد',
    destination: 'یزد',
    missionDate: '2026-06-17',
    status: 'Cancelled',
  },
];
export const InsurancesMock = [
  {
    id: 1,
    vehicleId: 1,
    vehicleName: 'ولوو FH500',
    insuranceCompany: 'بیمه ایران',
    policyNumber: 'IR-145632',
    expireDate: '2026-05-12',
    remainDays: 25,
    status: 'Warning',
  },
  {
    id: 2,
    vehicleId: 2,
    vehicleName: 'اسکانیا R450',
    insuranceCompany: 'آسیا',
    policyNumber: 'AS-245781',
    expireDate: '2026-04-22',
    remainDays: 5,
    status: 'Critical',
  },
  {
    id: 3,
    vehicleId: 3,
    vehicleName: 'ایسوزو NPR',
    insuranceCompany: 'البرز',
    policyNumber: 'AL-852147',
    expireDate: '2026-09-18',
    remainDays: 145,
    status: 'Active',
  },
];
export const ServiceReminderMock = [
  {
    id: 1,
    vehicleId: 1,
    vehicleName: 'ولوو FH500',
    serviceType: 'تعویض روغن',
    currentKm: 248500,
    serviceKm: 250000,
    remainKm: 1500,
    status: 'Warning',
  },
  {
    id: 2,
    vehicleId: 3,
    vehicleName: 'اسکانیا R450',
    serviceType: 'بازدید ترمز',
    currentKm: 179800,
    serviceKm: 180000,
    remainKm: 200,
    status: 'Critical',
  },
  {
    id: 3,
    vehicleId: 2,
    vehicleName: 'ایسوزو NPR',
    serviceType: 'تعویض فیلتر',
    currentKm: 95000,
    serviceKm: 10,
    remainKm: 5000,
    status: 'Active',
  },
];
export const AlertsMock = [
  {
    id: 1,
    vehicleId: 1,

    driverId: 2,

    missionId: 1,
    severity: 'error',
    title: 'Vehicle Insurance',
    description: 'Insurance has expired.',
  },

  {
    id: 2,
    vehicleId: 1,

    driverId: 2,

    missionId: 1,
    severity: 'هشدار',
    title: 'Vehicle Service',
    description: '3 vehicles need service.',
  },

  {
    id: 3,
    vehicleId: 2,

    driverId: 2,

    missionId: 2,

    severity: 'warning',
    title: 'Expenses',
    description: '5 expenses are waiting approval.',
  },

  {
    id: 4,
    vehicleId: 3,

    driverId: 2,

    missionId: 3,
    severity: 'info',
    title: 'Mission',
    description: '12 missions registered today.',
  },
];
