export const statusLabels = {
  TankFull: 'باک پر',
  TankNotFull: 'باک پر نیست',
  Approved: 'تایید شده',
  Pending: 'در انتظار تایید',
  Planned: 'برنامه‌ریزی‌شده',
  Rejected: 'رد شده',
  Conditional: 'مشروط',
  Active: 'فعال',
  Inactive: 'غیرفعال',
  Running: 'در حال انجام',
  Completed: 'تکمیل شده',
  Mission: 'در مأموریت',
  Repair: 'در تعمیرگاه',
  Canceled: 'لغو شده',
  Cancelled: 'لغو شده',
  Warning: 'هشدار',
  Critical: 'هشدار آخر',
  Expired: 'منقضی شده',
  Required: 'نیازمند سرویس',
  Overdue: 'معوق',
  ServiceCompleted: 'انجام شده',
  Success: 'تایید شده',
  warning: 'هشدار',
  error: 'هشدار جدی',
  primary: 'در عملیات',
  InRepair: 'در حال تعمیر',
  Sold: 'فروخته‌شده',
  ExpiringSoon: 'نزدیک به انقضا',
};

export const getStatusLabel = (status) => statusLabels[status] ?? status;
